title: Physical Computing
subtitle: MA Comp Arts
description: Charlotte Dann's programming blog for Physical Computing, a module of Goldsmiths' MA Comp Arts, taught by Phoenix Perry

socials:
  twitter: charlotte_dann
  codepen: pouretrebelle
  github: pouretrebelle
  rss: true

url:

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
